- name: Install Tomcat
  hosts: tomcat_servers
  become: true
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-18-jre-headless
        state: present

    - name: add tomcat group
      group:
        name: tomcat

    - name: add tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no
    - name: create /opt/tomcat directory
      file:
       path: /opt/tomcat
       state: directory
       mode: 0755
         
    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: Change ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
    - name: Start Tomcat Service
      shell: /opt/tomcat/apache-tomcat-9.0.54/bin/catalina.sh start
