---
- name: Deploy Application to Tomcat
  hosts: server
  become: yes

  vars:
    tomcat_webapps: /opt/tomcat/webapps
    war_file: /tmp/sample.war
    tomcat_user: tomcat
    tomcat_group: tomcat    
    
  tasks:

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Remove old application
      file:
        path: "{{ tomcat_webapps }}/myapp"
        state: absent

    - name: Copy WAR file
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_webapps }}/"
        mode: '0644'
        remote_src: True
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Start Tomcat
      shell: sudo -u tomcat /opt/tomcat/bin/startup.sh
